name: sync-jd_scripts
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'
jobs:
  sync:
    runs-on: ubuntu-18.04
    if: github.repository == 'RikudouPatrickstar/jd_scripts'
    timeout-minutes: 2
    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
    - name: Prepare Key
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - name: Clone Master
      run: |
        git clone -b master git@gitee.com:lxk0301/jd_scripts.git master
    - name: Push Master
      uses: ad-m/github-push-action@master
      with:
        directory: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
